name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@58077d3c7e43986b6b15fba718e8ea69e387dfcc # v2.15.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: ".nvmrc"

      - name: Dump version
        run: |
          node -v
          npm --version
          git --version

      - run: npm ci --ignore-scripts

      - name: npm audit
        run: |
          npm audit > ./audit.log || true
          if ! [ "$(cat ./audit.log | wc -l)" = 1 ]; then
            echo "::warning::$(cat ./audit.log)"
          fi
          rm ./audit.log

      - name: Run prettier
        run: npm run format:check

      - name: Run eslint
        run: npm run lint

      - run: npm test